name: 'Build CIRCT-HLS'
description: 'This action checks out and builds CIRCT-HLS and its dependencies.'
author: 'circt-hls'

inputs:
    cache-version:
        required: false
        description: 'used for refreshing the cache by simply changing value to something new'
        default: '1'
    cc:
        required: false
        description: 'C compiler to use'
        default: 'clang'
    cxx:
        required: false
        description: 'C++ compiler to use'
        default: 'clang++'
    build-type:
        required: false
        description: 'CMake build type'
        default: 'Release'


runs:
    using: 'composite'
    steps:
    - name: Install Python requirements
      shell: bash
      run: |
        pip3 install -r requirements.txt

    - name: Get rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    # Checkout verilator. We build verilator ourselves due to needing a recent
    # version - more recent than that which is available through apt-get.
    - name: Checkout Verilator
      uses: actions/checkout@v2
      with:
        repository: verilator/verilator
        path: verilator
        submodules: 'recursive'
        fetch-depth: 1
        ref: stable
    
    - name: Cache Verilator
      id: cache-verilator
      uses: actions/cache@v2
      with:
        path: |
          verilator/bin
          verilator/src/obj_dbg
          verilator/src/obj_opt
        key: ${{ inputs.build-type }}-${{ runner.os }}-verilator-${{ hashFiles('verilator/.git/HEAD') }}

    # Build Verilator. We don't do this conditionally on the cache since we still
    # need to install it into path.
    - name: Verilator build
      env:
          CC: ${{ inputs.cc }}
          CXX: ${{ inputs.cxx }}
      shell: bash
      run: |
        apt-get install -y git perl python3 make autoconf g++ flex bison
        apt-get install -y libgoogle-perftools-dev numactl perl-doc ccache
        apt-get install -y libfl2 libfl-dev zlibc zlib1g zlib1g-dev
        cd verilator
        autoconf
        ./configure
        make -j $(nproc)
        make install

    - name: Read circt tag file
      id: circt-ref
      uses: juliangruber/read-file-action@v1
      with:
        path: ./circt_tag.txt

    # Checkout CIRCT. This also checks out CIRCTs LLVM submodule
    - name: Checkout CIRCT
      uses: actions/checkout@v2
      with:
        repository: llvm/circt
        path: circt    
        ref: ${{ steps.circt-ref.outputs.content }}
        submodules: 'recursive'
        fetch-depth: 1

    # Cache the LLVM submodule inside CIRCT
    - name: Cache CIRCT LLVM/MLIR
      id: cache-circt-llvm
      uses: actions/cache@v2
      with:
        path: circt/llvm/build
        key: ${{ inputs.build-type }}-${{ runner.os }}-circt-llvm-${{ hashFiles('circt/.git/modules/llvm/HEAD') }}

    # Build LLVM+MLIR
    - name: CIRCT LLVM+MLIR build
      if: steps.cache-circt-llvm.outputs.cache-hit != 'true'
      env:
          CC: ${{ inputs.cc }}
          CXX: ${{ inputs.cxx }}
      shell: bash
      run: |
        mkdir -p circt/llvm/build
        cd circt/llvm/build
        cmake -G Ninja ../llvm \
            -DLLVM_BUILD_EXAMPLES=OFF \
            -DLLVM_ENABLE_BINDINGS=OFF \
            -DBUILD_SHARED_LIBS=ON \
            -DLLVM_ENABLE_LLD=ON \
            -DLLVM_OPTIMIZED_TABLEGEN=ON \
            -DLLVM_ENABLE_PROJECTS="mlir" \
            -DLLVM_TARGETS_TO_BUILD="host" \
            -DLLVM_ENABLE_ASSERTIONS=ON \
            -DCMAKE_BUILD_TYPE=Release
        ninja -j$(nproc)

    # Cache CIRCT itself
    - name: Cache CIRCT
      id: cache-circt
      uses: actions/cache@v2
      with:
        path: circt/build
        key: ${{ inputs.build-type }}-${{ runner.os }}-circt-${{ inputs.cache-version }}-${{ hashFiles('circt/.git/refs/heads/main') }}

    # Build CIRCT
    - name: CIRCT build
      shell: bash
      if: steps.cache-circt.outputs.cache-hit != 'true'
      env:
          CC: ${{ inputs.cc }}
          CXX: ${{ inputs.cxx }}
      run: |
        mkdir -p circt/build
        cd circt/build
        cmake -G Ninja .. \
          -DMLIR_DIR=$PWD/../llvm/build/lib/cmake/mlir \
          -DLLVM_DIR=$PWD/../llvm/build/lib/cmake/llvm \
          -DLLVM_ENABLE_ASSERTIONS=ON \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
        ninja -j$(nproc)

    # STEP 2: Build Polygeist + LLVM + MLIR. We do this separately from the CIRCT
    # build since there are often API-breaking changes between the two versions...
    # Checkout already done due to Polygeist being a submodule
    - name: Cache Polygeist MLIR+LLVM
      id: cache-polygeist-llvm
      uses: actions/cache@v2
      with:
        path: Polygeist/llvm-project/build
        key: ${{ inputs.build-type }}-${{ runner.os }}-polygeist-llvm-v3-${{ hashFiles('.git/modules/Polygeist/modules/llvm-project/HEAD') }}

    - name: Polygeist LLVM+MLIR build
      shell: bash
      if: steps.cache-polygeist-llvm.outputs.cache-hit != 'true'
      env:
          CC: ${{ inputs.cc }}
          CXX: ${{ inputs.cxx }}
      run: |
        mkdir -p Polygeist/llvm-project/build
        cd Polygeist/llvm-project/build
        cmake ../llvm -GNinja \
          -DLLVM_ENABLE_PROJECTS="llvm;clang;mlir;openmp" \
          -DBUILD_SHARED_LIBS=ON \
          -DLLVM_ENABLE_LLD=ON \
          -DLLVM_OPTIMIZED_TABLEGEN=ON \
          -DCMAKE_BUILD_TYPE=${{ inputs.build-type }} \
          -DCMAKE_CXX_FLAGS="-Wno-c++11-narrowing"
        ninja -j$(nproc)

    - name: Cache Polygeist
      id: cache-polygeist
      uses: actions/cache@v2
      with:
        path: Polygeist/build
        key: ${{ inputs.build-type }}-${{ runner.os }}-polygeist-v2-${{ hashFiles('.git/modules/Polygeist/HEAD') }}

    - name: Build Polygeist
      shell: bash
      if: steps.cache-polygeist.outputs.cache-hit != 'true'
      env:
            CC: ${{ inputs.cc }}
            CXX: ${{ inputs.cxx }}
      run: |
        mkdir -p Polygeist/build
        cd Polygeist/build
        cmake -G Ninja .. \
          -DMLIR_DIR=$PWD/../llvm-project/build/lib/cmake/mlir \
          -DCLANG_DIR=$PWD/../llvm-project/build/lib/cmake/clang \
          -DLLVM_TARGETS_TO_BUILD="host" \
          -DLLVM_ENABLE_ASSERTIONS=ON \
          -DCMAKE_BUILD_TYPE=${{ inputs.build-type }}
        ninja -j$(nproc)
        ninja mlir-clang

    # # Step 3: Calyx setup
    # - name: Calyx setup
    #   run: bash calyx_setup.sh


    # Step 4: CIRCT-HLS build
    # Cache CIRCT itself
    - name: Cache CIRCT-HLS
      id: cache-circt-hls
      uses: actions/cache@v2
      with:
        path: build
        key: ${{ inputs.build-type }}-${{ runner.os }}-circt-hls-v2-${{ hashFiles('.git/refs/heads/main') }}

    # Build CIRCT-HLS
    - name: CIRCT-HLS build
      shell: bash
      if: steps.cache-circt-hls.outputs.cache-hit != 'true'
      env:
          CC: ${{ inputs.cc }}
          CXX: ${{ inputs.cxx }}
      run: |
        ls Polygeist/build/bin
        mkdir -p build
        cd build
        cmake -G Ninja .. \
          -DCIRCT_DIR=$PWD/../circt/build/lib/cmake/circt \
          -DMLIR_DIR=$PWD/../circt/llvm/build/lib/cmake/mlir \
          -DLLVM_DIR=$PWD/../circt/llvm/build/lib/cmake/llvm \
          -DLLVM_ENABLE_ASSERTIONS=ON \
          -DCMAKE_BUILD_TYPE=${{ inputs.build-type }}
        ninja -j$(nproc)
