name: Build CIRCT-HLS

on:
  push:
    branches:
      - main
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  build:
    container:
      image: ghcr.io/circt/images/circt-ci-build:20211130162811
    name: Build ${{ matrix.build }} ${{ matrix.os }} ${{ matrix.compiler }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        build: ["Release"] #, "Debug"] # "RelWithDebInfo"
        os: [ubuntu-latest]
        compiler:
          - cc: clang
            cxx: clang++

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
        submodules: 'recursive'

    - name: Build CIRCT-HLS
      uses: ./.github/workflows/actions/build_circt_hls
      with:
        cache-version: ${{ secrets.CIRCT_CACHE_VERSION }}
        cc: ${{ matrix.compiler.cc }}
        cxx: ${{ matrix.compiler.cxx }}
        build-type: ${{ matrix.build }}
